import Head from 'next/head';
import Gallery from '../components/Gallery';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Hero
        title="Captur Photography"
        text="Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Amet blanditiis laudantium deleniti dolore? Quasi fuga
        expedita, ut beatae qui illum."
      />

      <Gallery />

      <Instagram />
    </div>
  );
}
